= Conclusie 
De bewijsstukken wijzen samen op één gebeurtenis: het lift-programma is op afstand bewust gemanipuleerd. De netwerkcapture laat zien dat het werkstation van Employee-01 rechtstreeks met de PLC van de lift communiceerde, iets wat een gewone medewerker nooit hoeft te doen. Dit is dus de afwijkende verbinding (*DV1*). Vanaf dat werkstation werd de PLC overgenomen, stilgezet en is het programma meerdere keren overschreven; dat zijn duidelijke sporen van ongeautoriseerde toegang (*DV2*).
 
De inhoud van die wijzigingen is zowel in het netwerkverkeer als in het geheugen van de PLC teruggevonden. In beide bronnen is dezelfde gang van zaken zichtbaar: het originele programma werd vervangen door een aangepaste versie met onder meer de verdachte tekst `attaxk`, gewijzigde timerinstellingen en een nieuwe projectnaam `SAFE Lab Mafia`. Daarna zijn die wijzigingen grotendeels teruggedraaid, waarbij alleen de naam als spoor achterbleef (*DV3*). De PLC verkeerde op dat moment dus in een aangepaste toestand die het gedrag van de lift kan hebben verstoord (*DV4*). De CCTV-beelden bevestigen dat: de lift liep vast en bewoog daarna met open deuren tussen de verdiepingen, met Kristi als slachtoffer.
 
Op de desktop van Kristi zijn geen sporen gevonden die met de aanval te maken hebben. Er is geen verband met het incident (*DV5*) en de software hierop heeft geen aantoonbare rol gespeeld (*DV6*). De desktopdump is gemaakt op 22 juni 2023, terwijl de netwerkcapture, de PLC-dumps en de CCTV-beelden van rond 29 juni dateren. De desktopdump valt dus ongeveer een week vóór het incident en bevat hierdoor mogelijk ook geen sporen van de aanval. Daarmee heeft dit bewijsstuk weinig waarde voor het reconstrueren van de gebeurtenis. De bron van de aanval is zeer waarschijnlijk ook niet Kristi, maar Employee-01. 

De kernbevindingen van McElevatorface zijn hiermee langs bevestigd, maar hun rapport schiet op meerdere punten tekort (*DV7*). De belangrijkste tekortkoming is hun eindconclusie: zij stellen dat niet met zekerheid te zeggen is of er sprake was van kwaadwillige manipulatie. Gezien de verdachte tekst `attaxk`, de aangepaste besturingslogica en het duidelijke patroon van aanval en sporenverwijdering is dat veel te voorzichtig. Daarnaast is hun onderbouwing op onderdelen zwak: wijzigingen worden vaag omschreven als "delen verwijderd en vervangen", terwijl concrete en cruciale aanpassingen ontbreken. De experimenten zijn slecht vastgelegd en bevatten onverklaarde functiecodes, en hun aanname dat bepaalde gegevens niet in de desktopdump aanwezig waren, blijkt bij controle onjuist.

Daarmee is ook de hoofdvraag beantwoord: de conclusies van McElevatorface zijn in de basis reproduceerbaar, maar onvolledig onderbouwd en op de belangrijkste vraag te terughoudend. Het bewijs versterkt de conclusie dat er zeer waarschijnlijk een gerichte aanval op de lift heeft plaatsgevonden. 

