= Samenvatting
In dit onderzoek is een onafhankelijke validatie uitgevoerd van het eindrapport van onderzoeksgroep McElevatorface binnen de DFRWS 2023 Challenge *The Troubled Elevator*. Het doel was vast te stellen in hoeverre de oorspronkelijke bevindingen reproduceerbaar en valide zijn aan de hand van dezelfde bewijsstukken: een netwerkcapture, PLC-memorydumps, een desktop-memorydump en CCTV-beelden.

Ter ondersteuning van de analyse zijn experimenten uitgevoerd met een Schneider Modicon M221 PLC. Hiermee zijn relevante UMAS-functiecodes gevalideerd en is vastgesteld welke netwerkhandelingen horen bij het claimen, stoppen, starten, uploaden en overschrijven van PLC-programma’s. Deze referentie maakte het mogelijk om de handelingen in de aangeleverde netwerkcapture betrouwbaar te interpreteren.

Uit de netwerkanalyse bleek dat het werkstation van Employee-01 rechtstreeks communiceerde met de PLC van de lift. Daarbij werden functiecodes aangetroffen die overeenkomen met het overnemen van de PLC, het stoppen van het programma en het overschrijven van de aanwezige logica. Daarnaast zijn door middel van file carving ZIP-archieven gereconstrueerd uit TCP-streams binnen de netwerkcapture. Deze archieven bevatten meerdere versies van het PLC-project die tijdens de communicatie tussen het werkstation en de PLC zijn overgedragen. Hierdoor kon niet alleen worden vastgesteld dát wijzigingen hebben plaatsgevonden, maar ook welke wijzigingen daadwerkelijk zijn aangebracht.

De analyse van de PLC-memorydumps bevestigde deze bevindingen. Zowel in het netwerkverkeer als in de ExternalRAM-dumps werden dezelfde projectversies teruggevonden. Vergelijking van deze versies liet zien dat het oorspronkelijke programma expres was aangepast. Daarbij werden onder meer timerinstellingen gewijzigd, extra programmalogica toegevoegd en verscheen de tekst *attaxk* in de projectbestanden. Ook werd de projectnaam gewijzigd naar *SAFE Lab Mafia*. In latere versies bleken diverse wijzigingen weer te zijn verwijderd, terwijl andere aanpassingen behouden bleven. Dit patroon wijst op een poging om de aangebrachte wijzigingen gedeeltelijk te verbergen nadat deze waren uitgevoerd.

De analyse van de desktop-memorydump van Kristi leverde geen aanwijzingen op voor betrokkenheid bij de aanval. Tevens werden geen artefacten aangetroffen die direct verband houden met de manipulatie van de PLC. Omdat deze memorydump ongeveer een week voor het incident is gemaakt, blijkt dit bewijsstuk van beperkte waarde voor de reconstructie van de gebeurtenis. De CCTV-beelden bevestigen dat de lift vastliep en vervolgens met open deuren tussen de verdiepingen bewoog, waarbij Kristi het slachtoffer werd van het incident.

De belangrijkste conclusies van McElevatorface blijken reproduceerbaar, maar de onderbouwing in het oorspronkelijke rapport is op meerdere punten onvolledig. Door de reconstructie van PLC-projectbestanden uit het netwerkverkeer en de gedetailleerde vergelijking van opeenvolgende PLC-memorydumps kon nauwkeuriger worden vastgesteld welke wijzigingen zijn aangebracht en later weer zijn verwijderd. Waar McElevatorface terughoudend concludeert dat kwaadwillige manipulatie niet met zekerheid kan worden vastgesteld, wijzen de gecombineerde bevindingen juist op een duidelijk patroon van manipulatie en sporenverwijdering.

Op basis van alle onderzochte bewijsstukken wordt geconcludeerd dat de lift met grote waarschijnlijkheid op afstand is gemanipuleerd vanaf het werkstation van Employee-01. De resultaten ondersteunen daarmee het scenario van gerichte sabotage via het netwerk en maken alternatieve verklaringen, zoals een spontane storing, stroomuitval of fysieke manipulatie, aanzienlijk minder waarschijnlijk.
